baseURL: "https://devsparks.goooseman.dev"
languageCode: "en-us"
title: "DevSparks"
theme: "devsparks"
relativeUrls: true

params:
  dateFormat: "January 2, 2006"

menu:
  main:
    - name: "Hacks"
      url: "/"
      weight: 10
      identifier: "hacks"
    - name: "About"
      url: "/about/"
      weight: 20
      identifier: "about"
    - name: "GitHub"
      url: "https://github.com/goooseman/devsparks-blog"
      weight: 30
      identifier: "github"

module:
  mounts:
    - source: "../../content"
      target: "content"
    - source: "../../static"
      target: "static"