# DevSparks Blog Specification

# site configuration for Hugo

baseURL = "https://devsparks-blog.com"
languageCode = "en-us"
title = "DevSparks Blog"
theme = "devsparks"

# languages
[languages]
  [languages.en]
    languageName = "English"
    weight = 1

# metadata
copyright = "© 2022 DevSparks Blog. All Rights Reserved."
googleAnalytics = "UA-XXX-XX"

# taxonomies
[taxonomies]
  tag = "tags"
  category = "categories"

# main menu
[[menu.main]]
  name = "Home"
  url = "/"
  weight = 1

[[menu.main]]
  name = "Hacks"
  url = "/hacks/"
  weight = 2

[[menu.main]]
  name = "About"
  url = "/about/"
  weight = 3

# output formats
[outputFormats]
  [outputFormats.RSS]
    mediatype = "application/rss+xml"
    baseName = "rss"
    title = "DevSparks RSS Feed"

# content types
[contentTypes]
  [contentTypes.hack]
    outputs = ["HTML", "RSS"]
    isCJKLanguage = true
    image = "/images/placeholder.png"

# params
[params]
  author = "Alex"
  amber = "#ffc000"
  toggle_on = "Dark"
  toggle_off = "Light"
  dark_mode_class = "dark"
  light_mode_class = "light"