baseURL: "https://devsparks.goooseman.dev"
title: "DevSparks"
theme: "devsparks"
relativeUrls: true

params:
  dateFormat: "January 2, 2006"

menu:
  main:
    - name: "Hacks"
      url: "/"
      identifier: "hacks"
      weight: 10
    - name: "About"
      url: "/about/"
      identifier: "about"
      weight: 20
    - name: "GitHub"
      url: "https://github.com/goooseman/devsparks-blog"
      identifier: "github"
      weight: 30

module:
  mounts:
    - source: "../../content"
      target: "content"
    - source: "../../static"
      target: "static"