baseURL = "https://devsparks.goooseman.dev/"
languageCode = "en-us"
title = "DevSparks Blog"
theme = "devsparks"

[module]
  [[module.mounts]]
    source = "../../content"
    target = "content"
  [[module.mounts]]
    source = "../../static"
    target = "static"
