baseURL: "https://devsparks.goooseman.dev"
title: "DevSparks"
theme: "devsparks"
relativeUrls: true

params:
  dateFormat: "January 2, 2006"

menu:
  main:
    - name: "GitHub"
      url: "https://github.com/goooseman/devsparks-blog"
      identifier: "github"
      weight: 30
      post: "⧉"

module:
  mounts:
    - source: "../../content"
      target: "content"
    - source: "../../static"
      target: "static"
  
markup:
  goldmark:
    renderer:
      unsafe: true