baseURL = "https://devsparks.goooseman.dev"
languageCode = "en-us"
title = "DevSparks Blog"
theme = "devsparks"

[module]
  [[module.mounts]]
    source = "../../content"
    target = "content"
  [[module.mounts]]
    source = "../../static"
    target = "static"

[params]
  dateFormat = "January 2, 2006"

[outputFormats]
  [outputFormats.RSS]
    mediaType = "application/rss+xml"
    baseName = "index"
    isPlainText = false
    notAlternative = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[menu]
  [[menu.main]]
    identifier = "hacks"
    name = "Hacks"
    url = "/"
    weight = 1
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 2
  [[menu.main]]
    identifier = "github"
    name = "GitHub"
    url = "https://github.com/goooseman/devsparks-blog"
    weight = 3

