baseURL = "https://devsparks.goooseman.dev"
languageCode = "en-us"
title = "DevSparks Blog"
theme = "devsparks"

[params]
  dateFormat = "January 2, 2006"

[markup]
  [markup.goldmark.renderer]
    unsafe = true

[[menu.main]]
  name = "Hacks"
  url = "/"
  weight = 1

[[menu.main]]
  name = "About"
  url = "/about"
  weight = 2