baseURL = "https://devsparks.goooseman.dev"
languageCode = "en-us"
title = "DevSparks"
theme = "devsparks"

[params]
  dateFormat = "January 2, 2006"

[[menu.main]]
  name = "Hacks"
  url = "/"
  weight = 1

[[menu.main]]
  name = "About"
  url = "/about"
  weight = 2

[[menu.main]]
  name = "GitHub"
  url = "https://github.com/goooseman/devsparks-blog"
  weight = 3