baseURL = "https://devsparks.goooseman.dev"
languageCode = "en-us"
title = "DevSparks Blog"
theme = "devsparks"

[params]
  dateFormat = "January 2, 2006"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[outputFormats]
  [outputFormats.REMARK42]
    mediaType = "text/html"
    baseName = "index"
    isHTML = true
    notAlternative = true
    permalinkable = false
    path = "remark42"

[outputs]
  home = ["HTML", "REMARK42"]
  section = ["HTML"]
  taxonomy = ["HTML"]
  term = ["HTML"]