version: '3.8'
services:
  hugo:
    image: klakegg/hugo:0.89.4
    volumes:
      - .:/src
    ports:
      - 1313:1313
    command: server --bind 0.0.0.0 --disableFastRender

  remark42:
    image: umputun/remark42:latest
    environment:
      - REMARK_URL=https://remark42.goooseman.dev
      - SITE=dev_sparks
      - SECRET=some-secret-key
      - AUTH_ANON=true
    volumes:
      - ./data:/srv/var
    ports:
      - 8080:8080